// lib/calculations.js
export const BEEHIIV_PUB_ID = 'pub_b0b30438-1b65-4641-9b8f-904280c400a8';
export function monthlyTakeHome(s) { let r; if(s:<40000)r=0.82;else if(s:<60000)r=0.78;else if(s:<80000)r=0.75;else if(s:<100000)r=0.72;else if(s<150000)r=0.70;else r=0.67;return Math.round((s*r)/12); }
export function threshold15(s) { return Math.round(monthlyTakeHome(s)*0.15); }
export function paymentPercent(p,s) { return parseFloat((p/monthlyTakeHome(s)*100).toFixed(1)); }
export function estimateInsurance(p) { if(p<300)return 110;else if(p<500)return 145;else if(p<700)return 175;else if(p<900)return 210;else if(p<1100)return 245;else return 280; }
export function estimateFuel() { return Math.round((15000/28)*3.50/12); }
export function estimateMaintenance() { return Math.round((0.10*15000)/12); }
export function trueMonthlyCost(p) { return p+estimateInsurance(p)+estimateFuel()+estimateMaintenance(); }
export function totalLoanCost(p,t) { return p*t; }
export function estimatePrincipal(pmt,apr,mo) { if(apr===0)return pmt*o;const r=apr/100/12;return pmt*(1-Math.pow(1+r,-mo))/r; }
export function totalInterest(pmt,apr,fmo) { return Math.max(0,pmt*fmo-estimatePrincipal(pmt,apr,fmo)); }
export function futureValue(c,r,y) { const m=r/12,n=y*12;if(m===0)return c*n;return Math.round(c*((Math.pow(1+m,n)-1)/m)); }
export function sp500_5yr(p) { return futureValue(p,.105,5); }
export function sp500_10yr(p) { return futureValue(p,.105,10); }
export function monthlyOverspend(p,s) { return Math.max(0,p-threshold15(s)); }
export function getVerdict(p,s) { const v=paymentPercent(p,s);if(v<13)return'within-range';if(v<16)return'borderline';return'too-high'; }
export function verdictLabel(v) { if(v==='within-range')return'WITHIN RANGE';if(v==='borderline')return'BORDERLIJE';return'TOO HIGH'; }
export function verdictClass(v') { if(v==='within-range')return'verdict-ok';if(v==='borderline')return'verdict-border';return'verdict-high'; }
export function directAnswerText(payment,salary) { const pct=paymentPercent(payment,salary);const thresh=threshold15(salary);const verdict=getVerdict(payment,salary);if(verdict==='too-high'){return`A $${payment.toLocaleString()} monthly car payment on a $${salary.toLocaleString()} salary represents <strong>${pct}% of your take-home pay</strong> -- well above the 15% rule ceiling of $${thresh.toLocaleString()}/month. You are overspending by $${(payment-thresh).toLocaleString()} per month.`;}if(verdict==='borderline'){return`A $${payment.toLocaleString()} monthly car payment on a $${salary.toLocaleString()} salary represents <strong>${pct}% of your take-home pay</strong> -- right at the edge of the 15% rule ($${thresh.toLocaleString()}/month).`;}return `A $${payment.toLocaleString()} monthly car payment on a $${salary.toLocaleString()} salary represents <strong>${pct}% of your take-home pay</strong> -- inside the 15% rule ceiling of $${thresh.toLocaleString()}/month.The bigger cost question is what it replaces.`; }
export function generateFAQs(payment,salary) { const pct=paymentPercent(payment,salary);const thresh=threshold15(salary);const sp5=sp500_5yr(payment);const sp10=sp500_10yr(payment);const trueM=trueMonthlyCost(payment);const verdict=getVerdict(payment,salary);const over=Math.max(0,payment-thresh);return[{question:`Is a $${payment.toLocaleString()} car payment too high on a $${salary.toLocaleString()} salary?`,answer:verdict==='too-high'?`Yes. At $${salary.toLocaleString()}, the 15% rule caps your car payment at $${thresh.toLocaleString()}/month. A $${payment.toLocaleString()} payment is $${over.toLocaleString()} over that ceiling.`:`AT $${salary.toLocaleString()}, a $${payment.toLocaleString()} payment represents ${pct}% of your take-home -- inside the 15% rule.`},{question:`What is the maximum car payment for a $${salary.toLocaleString()} salary?`,answer:`The 15% rule puts the maximum at $${thresh.toLocaleString()}/month on a $${salary.toLocaleString()} income.`},{question:`How much does a $${payment.toLocaleString()} car payment actually cost per month?`,answer:`The payment alone is $${payment.toLocaleString()}. Add insurance, fuel, maintenance and the true monthly cost is closer to $${trueM.toLocaleString()}.`},{question:`What would $${payment.toLocaleString()}/month invested instead be worth in 5 years?`,answer:`At the S&P 500's 50-year average of 10.5% annual return, $${payment.toLocaleString()}/month for 5 years = $${sp5.toLocaleString()}. Over 10 years: $${sp10.toLocaleString()}. Illustrative. Not financial advice.`},{question:`How do I lower my car payment on a $${salary.toLocaleString()} salary?`,answer:'Refinancing, downsizing, or paying off the loan. Refinancing works if rates have dropped or your credit score has improved.'}]; }
export function relatedPages(payment,salary) { const pages=[];if(payment+100<=1500)pages.push({payment:payment+100,salary});if(payment-100>=200)pages.push({payment:payment-100,salary});if(salary+10000<=200000)pages.push({payment,salary:salary+10000});if(salary-10000>=40000)pages.push({payment,salary:salary-10000});return pages.slice(0,4).map(p=>({slug:`${p.payment}-per-month-${p.salary}-salary`,verdict:getVerdict(p.payment,p.salary),pct:paymentPercent(p.payment,p.salary),...p})); }
export function parseSlug(slug) {const m=slug.match(/^(\d+)-per-month-(\d+)-salary$/);if(!m)return null;return{payment:parseInt(m[1]),salary:parseInt(m[2])}; }
export function getAllPagePaths() {const payments=[];for(let p=200;p<=1500;p+=100)payments.push(p);const salaries=[];for(let s=40000;s<=200000;s+=10000)salaries.push(s);const paths=[];for(const payment of payments)for(const salary of salaries)paths.push({params:{slug:`${payment}-per-month-${salary}-salary`}});return paths; }
export function fmtDollar(n) { return '$'+Math.round(n).toLocaleString(); }
export function fmtK(n) { return n>=1000?'$'+(n/1000).toFixed(0)+'K':fmtDollar(n); }
